# Generated by Django 2.0 on 2018-07-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
